using Microsoft.Data.Sqlite;
using Microsoft.Web.WebView2.Core;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
namespace Luma;
public sealed record ChromeImportOptions(bool History,bool Bookmarks,bool Passwords,bool Autofill,bool OpenTabs,bool SearchEngine,bool Cookies);
public sealed class ChromeImportReport{public int Profiles,History,Bookmarks,Passwords,Autofill,Cookies,ProtectedPasswords,ProtectedCookies;public List<string> Tabs{get;}=[];public List<string> Warnings{get;}=[];}
public static class ChromeImporter
{
 private static readonly Regex UrlPattern=new("https?://[^\\x00-\\x20\\\"'<>]{4,2048}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
 public static async Task<ChromeImportReport> ImportAsync(SpaceState space,LumaState state,CoreWebView2CookieManager cookies,ChromeImportOptions o,Func<int,string,Task> progress)
 {
  var r=new ChromeImportReport();var root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Google","Chrome","User Data");if(!Directory.Exists(root))throw new DirectoryNotFoundException("Локальный профиль Google Chrome не найден.");var profiles=Directory.EnumerateDirectories(root).Where(x=>Path.GetFileName(x)=="Default"||Path.GetFileName(x).StartsWith("Profile ",StringComparison.OrdinalIgnoreCase)).ToList();if(profiles.Count==0)throw new DirectoryNotFoundException("Профили Chrome не найдены.");r.Profiles=profiles.Count;var key=ReadKey(Path.Combine(root,"Local State"));var creds=new List<ImportedCredential>();var fields=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var sites=new Dictionary<string,SavedSite>(StringComparer.OrdinalIgnoreCase);var history=new Dictionary<string,HistoryEntry>(StringComparer.OrdinalIgnoreCase);
  for(var i=0;i<profiles.Count;i++){var p=profiles[i];await progress(5+i*80/profiles.Count,$"Читаем {Path.GetFileName(p)}…");if(o.Bookmarks)Bookmarks(Path.Combine(p,"Bookmarks"),sites);if(o.History)History(Path.Combine(p,"History"),history,r);if(o.Passwords)Passwords(Path.Combine(p,"Login Data"),key,creds,r);if(o.Autofill)Autofill(Path.Combine(p,"Web Data"),fields,r);if(o.OpenTabs)Sessions(Path.Combine(p,"Sessions"),r.Tabs);if(o.SearchEngine)Search(Path.Combine(p,"Preferences"),state);if(o.Cookies)await Cookies(Path.Combine(p,"Network","Cookies"),key,cookies,r);}
  if(o.Bookmarks&&sites.Count>0){var f=space.Folders.FirstOrDefault(x=>x.Name=="Импорт Chrome")??new FolderState{Name="Импорт Chrome",Expanded=true};if(!space.Folders.Contains(f))space.Folders.Add(f);foreach(var s in sites.Values)if(!f.Items.Any(x=>string.Equals(x.Url,s.Url,StringComparison.OrdinalIgnoreCase)))f.Items.Add(s);r.Bookmarks=sites.Count;}
  if(o.History){foreach(var h in history.Values)if(!state.History.Any(x=>string.Equals(x.Url,h.Url,StringComparison.OrdinalIgnoreCase)))state.History.Add(h);state.History=state.History.OrderByDescending(x=>x.VisitedAt).Take(1500).ToList();r.History=history.Count;}if(o.Passwords)r.Passwords=CredentialVault.ImportCredentials(creds);if(o.Autofill)r.Autofill=CredentialVault.ImportAutofill(fields);var unique=r.Tabs.Where(x=>Uri.TryCreate(x,UriKind.Absolute,out var u)&&u.Scheme is "http" or "https").Distinct(StringComparer.OrdinalIgnoreCase).Take(20).ToList();r.Tabs.Clear();r.Tabs.AddRange(unique);if(r.ProtectedCookies+r.ProtectedPasswords>0)r.Warnings.Add("Часть новых данных Chrome защищена App-Bound Encryption. Windows запрещает другому приложению расшифровывать эти сеансы и пароли — они пропущены.");state.Save();await progress(100,"Импорт завершён");return r;
 }
 private static void Bookmarks(string file,Dictionary<string,SavedSite> result){if(!File.Exists(file))return;using var d=JsonDocument.Parse(File.ReadAllText(file));if(!d.RootElement.TryGetProperty("roots",out var roots))return;foreach(var p in roots.EnumerateObject())Walk(p.Value,result);}
 private static void Walk(JsonElement n,Dictionary<string,SavedSite> result){if(n.TryGetProperty("type",out var t)&&t.GetString()=="url"&&n.TryGetProperty("url",out var uv)){var u=uv.GetString()??"";if(Uri.TryCreate(u,UriKind.Absolute,out var uri)&&uri.Scheme is "http" or "https")result[u]=new(){Url=u,Title=n.TryGetProperty("name",out var name)?name.GetString()??uri.Host:uri.Host};}if(n.TryGetProperty("children",out var c))foreach(var x in c.EnumerateArray())Walk(x,result);}
 private static void History(string file,Dictionary<string,HistoryEntry> result,ChromeImportReport r){if(!File.Exists(file))return;var copy=CopyDb(file);try{using var c=new SqliteConnection($"Data Source={copy};Mode=ReadOnly");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT url,title,last_visit_time FROM urls WHERE hidden=0 ORDER BY last_visit_time DESC LIMIT 1200";using var rd=q.ExecuteReader();while(rd.Read()){var u=rd.GetString(0);if(!Uri.TryCreate(u,UriKind.Absolute,out var uri)||uri.Scheme is not("http" or "https"))continue;result[u]=new(){Url=u,Title=rd.IsDBNull(1)?uri.Host:rd.GetString(1),VisitedAt=Time(rd.GetInt64(2))};}}catch(Exception e){r.Warnings.Add("История: "+e.Message);}finally{Clean(copy);}}
 private static void Passwords(string file,byte[]? key,List<ImportedCredential> result,ChromeImportReport r){if(!File.Exists(file))return;var copy=CopyDb(file);try{using var c=new SqliteConnection($"Data Source={copy};Mode=ReadOnly");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT origin_url,username_value,password_value FROM logins";using var rd=q.ExecuteReader();while(rd.Read()){var value=Decrypt((byte[])rd[2],key,out var bound);if(value is null){if(bound)r.ProtectedPasswords++;continue;}result.Add(new(){Origin=rd.GetString(0),Username=rd.IsDBNull(1)?"":rd.GetString(1),Password=value});}}catch(Exception e){r.Warnings.Add("Пароли: "+e.Message);}finally{Clean(copy);}}
 private static void Autofill(string file,Dictionary<string,string> result,ChromeImportReport r){if(!File.Exists(file))return;var copy=CopyDb(file);try{using var c=new SqliteConnection($"Data Source={copy};Mode=ReadOnly");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT name,value FROM autofill ORDER BY date_last_used DESC LIMIT 500";using var rd=q.ExecuteReader();while(rd.Read())if(!rd.IsDBNull(0)&&!rd.IsDBNull(1))result[rd.GetString(0)]=rd.GetString(1);}catch(Exception e){r.Warnings.Add("Автозаполнение: "+e.Message);}finally{Clean(copy);}}
 private static async Task Cookies(string file,byte[]? key,CoreWebView2CookieManager manager,ChromeImportReport r){if(!File.Exists(file))return;var copy=CopyDb(file);try{using var c=new SqliteConnection($"Data Source={copy};Mode=ReadOnly");await c.OpenAsync();using var q=c.CreateCommand();q.CommandText="SELECT host_key,name,path,encrypted_value,expires_utc,is_secure,is_httponly,samesite FROM cookies";using var rd=await q.ExecuteReaderAsync();while(await rd.ReadAsync()){var host=rd.GetString(0);var value=Decrypt((byte[])rd[3],key,out var bound,host);if(value is null){if(bound)r.ProtectedCookies++;continue;}try{var ck=manager.CreateCookie(rd.GetString(1),value,host,rd.IsDBNull(2)?"/":rd.GetString(2));ck.IsSecure=rd.GetInt64(5)!=0;ck.IsHttpOnly=rd.GetInt64(6)!=0;var exp=rd.GetInt64(4);if(exp>0&&exp<long.MaxValue/10)ck.Expires=Time(exp);ck.SameSite=rd.IsDBNull(7)?CoreWebView2CookieSameSiteKind.None:rd.GetInt32(7) switch{1=>CoreWebView2CookieSameSiteKind.Lax,2=>CoreWebView2CookieSameSiteKind.Strict,_=>CoreWebView2CookieSameSiteKind.None};manager.AddOrUpdateCookie(ck);r.Cookies++;}catch{}}}catch(Exception e){r.Warnings.Add("Cookie: "+e.Message);}finally{Clean(copy);}}
 private static void Sessions(string folder,List<string> result){if(!Directory.Exists(folder))return;foreach(var f in Directory.EnumerateFiles(folder).OrderByDescending(File.GetLastWriteTimeUtc).Take(4))try{var text=Encoding.UTF8.GetString(File.ReadAllBytes(f));foreach(Match m in UrlPattern.Matches(text))result.Add(m.Value.TrimEnd('.',',',';',')',']','}'));}catch{}}
 private static void Search(string file,LumaState state){try{using var d=JsonDocument.Parse(File.ReadAllText(file));var raw=d.RootElement.TryGetProperty("default_search_provider",out var p)&&p.TryGetProperty("name",out var n)?n.GetString()??"":"";state.SearchEngine=raw.Contains("duck",StringComparison.OrdinalIgnoreCase)?"duckduckgo":raw.Contains("bing",StringComparison.OrdinalIgnoreCase)?"bing":"google";}catch{}}
 private static byte[]? ReadKey(string file){try{using var d=JsonDocument.Parse(File.ReadAllText(file));var b=Convert.FromBase64String(d.RootElement.GetProperty("os_crypt").GetProperty("encrypted_key").GetString()!);if(b.AsSpan().StartsWith("DPAPI"u8))b=b[5..];return ProtectedData.Unprotect(b,null,DataProtectionScope.CurrentUser);}catch{return null;}}
 private static string? Decrypt(byte[] data,byte[]? key,out bool bound,string? host=null){bound=data.AsSpan().StartsWith("v20"u8);if(bound)return null;try{byte[] clear;if((data.AsSpan().StartsWith("v10"u8)||data.AsSpan().StartsWith("v11"u8))&&key is not null){var cipher=data.AsSpan(15,data.Length-31);clear=new byte[cipher.Length];using var aes=new AesGcm(key,16);aes.Decrypt(data.AsSpan(3,12),cipher,data.AsSpan(data.Length-16,16),clear);}else clear=ProtectedData.Unprotect(data,null,DataProtectionScope.CurrentUser);if(host is not null&&clear.Length>32&&clear.AsSpan(0,32).SequenceEqual(SHA256.HashData(Encoding.UTF8.GetBytes(host))))clear=clear[32..];return Encoding.UTF8.GetString(clear);}catch{return null;}}
 private static string CopyDb(string source){var dir=Path.Combine(Path.GetTempPath(),"LumaImport",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var target=Path.Combine(dir,Path.GetFileName(source));File.Copy(source,target,true);foreach(var x in new[]{"-wal","-shm"})if(File.Exists(source+x))try{File.Copy(source+x,target+x,true);}catch{}return target;}private static void Clean(string file){try{Directory.Delete(Path.GetDirectoryName(file)!,true);}catch{}}private static DateTime Time(long micros){try{return DateTime.FromFileTimeUtc(checked(micros*10));}catch{return DateTime.UtcNow;}}
}
